In [150]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import re
import string
import numpy as np
from urllib.request import urlopen
import pandas as pd

pd.set_option('display.max_columns', None)

In [156]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd

class get_data:

    def dataset(self, season, mode):
        url = f'https://www.basketball-reference.com/leagues/NBA_{season}_{mode}.html'
        table_web = BeautifulSoup(urlopen(url), 'html.parser').findAll('table')

        df = pd.read_html(str(table_web))[0]  # Changed table_html to table_web
        #df = df.drop(df[df.Player == 'Player'].index)
        #df = df.drop('Rk', axis=1) # drop Rk columns
        #df.Player = df.Player.str.replace('*','',regex=True)
        df.insert(0,'Season',season) # insert season column
        df = df.apply(pd.to_numeric, errors='coerce').fillna(df)

        return df  # Added return statement to return the DataFrame

# Now, to call the dataset function:
dataset_obj = get_data()  # Instantiate the get_dataset object
season = '2022'  # Example season
mode = 'shooting'  # Example mode
result_df = dataset_obj.dataset(season, mode)  # Call the dataset method
result_df.columns = result_df.columns.get_level_values(1)
#result_df.columns = result_df.columns.get_level_values(1)
#result_df = result_df.drop(result_df.index[0])
result_df.reset_index(drop=True, inplace=True)
result_df.drop_duplicates(subset=result_df.columns[2], keep='first', inplace=True)
result_df = result_df.loc[:, ~result_df.columns.str.startswith('Unnamed')]
result_df.reset_index(drop=True, inplace=True)
result_df  # Display the resulting DataFrame

,,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,2P,0-3,3-10,10-16,16-3P,3P,2P,0-3,3-10,10-16,16-3P,3P,2P,3P,%FGA,#,%3PA,3P%,Att.,#
0,2022,1.0,Precious Achiuwa,C,22.0,TOR,73.0,1725.0,0.439,10.2,0.741,0.348,0.274,0.085,0.035,0.259,0.468,0.614,0.345,0.373,0.19,0.359,0.598,0.964,0.143,67.0,0.429,0.313,0.0,0.0
1,2022,2.0,Steven Adams,C,28.0,MEM,76.0,1999.0,0.547,2.9,0.997,0.693,0.26,0.042,0.003,0.003,0.548,0.632,0.35,0.438,0.0,0.0,0.49,NaN,0.143,48.0,0.0,NaN,1.0,0.0
2,2022,3.0,Bam Adebayo,C,24.0,MIA,56.0,1825.0,0.557,7.0,0.992,0.395,0.309,0.2,0.088,0.008,0.562,0.771,0.467,0.404,0.313,0.0,0.608,NaN,0.181,119.0,0.0,NaN,2.0,0.0
3,2022,4.0,Santi Aldama,PF,21.0,MEM,32.0,360.0,0.402,12.0,0.636,0.333,0.205,0.091,0.008,0.364,0.56,0.682,0.444,0.417,0.0,0.125,0.638,1.0,0.076,10.0,0.229,0.364,0.0,0.0
4,2022,5.0,LaMarcus Aldridge,C,36.0,BRK,47.0,1050.0,0.55,12.3,0.9,0.21,0.17,0.24,0.279,0.1,0.578,0.729,0.513,0.509,0.563,0.304,0.748,1.0,0.039,18.0,0.283,0.308,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,2022,601.0,Thaddeus Young,PF,33.0,TOT,52.0,845.0,0.518,7.7,0.824,0.382,0.393,0.026,0.022,0.176,0.554,0.625,0.523,0.286,0.167,0.354,0.524,1.0,0.037,7.0,0.604,0.483,0.0,0.0
602,2022,602.0,Trae Young,PG,23.0,ATL,76.0,2652.0,0.46,16.5,0.605,0.159,0.204,0.116,0.126,0.395,0.512,0.62,0.451,0.469,0.513,0.382,0.142,0.223,0.0,0.0,0.048,0.552,1.0,0.0
603,2022,603.0,Omer Yurtseven,C,23.0,MIA,56.0,706.0,0.526,5.8,0.955,0.437,0.385,0.113,0.02,0.045,0.547,0.722,0.432,0.357,0.0,0.091,0.783,1.0,0.178,39.0,0.182,0.0,0.0,0.0
604,2022,604.0,Cody Zeller,C,29.0,POR,27.0,355.0,0.567,3.7,0.956,0.644,0.267,0.033,0.011,0.044,0.593,0.621,0.542,0.333,1.0,0.0,0.725,NaN,0.211,16.0,0.25,0.0,0.0,0.0
605,2022,605.0,Ivica Zubac,C,24.0,LAC,76.0,1852.0,0.626,3.4,1.0,0.58,0.382,0.032,0.006,0.0,0.626,0.714,0.508,0.5,0.333,NaN,0.719,NaN,0.248,110.0,NaN,NaN,0.0,0.0

In [155]:
original_shooting = pd.read_csv('datasets/shootings_splits/SP_2021_2022.csv', keep_default_na=False, index_col=None)
original_shooting.columns = original_shooting.iloc[0]
original_shooting = original_shooting.drop(original_shooting.index[0])
original_shooting

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,,2P,0-3,3-10,10-16,16-3P,3P,,2P,0-3,3-10,10-16,16-3P,3P,,2P,3P,,%FGA,#,,%3PA,3P%,,Att.,#,-9999
1,1,Precious Achiuwa,C,22,TOR,73,1725,.439,10.2,,.741,.348,.274,.085,.035,.259,,.468,.614,.345,.373,.190,.359,,.598,.964,,.143,67,,.429,.313,,0,0,achiupr01
2,2,Steven Adams,C,28,MEM,76,1999,.547,2.9,,.997,.693,.260,.042,.003,.003,,.548,.632,.350,.438,.000,.000,,.490,,,.143,48,,.000,,,1,0,adamsst01
3,3,Bam Adebayo,C,24,MIA,56,1825,.557,7.0,,.992,.395,.309,.200,.088,.008,,.562,.771,.467,.404,.313,.000,,.608,,,.181,119,,.000,,,2,0,adebaba01
4,4,Santi Aldama,PF,21,MEM,32,360,.402,12.0,,.636,.333,.205,.091,.008,.364,,.560,.682,.444,.417,.000,.125,,.638,1.000,,.076,10,,.229,.364,,0,0,aldamsa01
5,5,LaMarcus Aldridge,C,36,BRK,47,1050,.550,12.3,,.900,.210,.170,.240,.279,.100,,.578,.729,.513,.509,.563,.304,,.748,1.000,,.039,18,,.283,.308,,0,0,aldrila01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,601,Thaddeus Young,PF,33,TOT,52,845,.518,7.7,,.824,.382,.393,.026,.022,.176,,.554,.625,.523,.286,.167,.354,,.524,1.000,,.037,7,,.604,.483,,0,0,youngth01
602,602,Trae Young,PG,23,ATL,76,2652,.460,16.5,,.605,.159,.204,.116,.126,.395,,.512,.620,.451,.469,.513,.382,,.142,.223,,.000,0,,.048,.552,,1,0,youngtr01
603,603,Omer Yurtseven,C,23,MIA,56,706,.526,5.8,,.955,.437,.385,.113,.020,.045,,.547,.722,.432,.357,.000,.091,,.783,1.000,,.178,39,,.182,.000,,0,0,yurtsom01
604,604,Cody Zeller,C,29,POR,27,355,.567,3.7,,.956,.644,.267,.033,.011,.044,,.593,.621,.542,.333,1.000,.000,,.725,,,.211,16,,.250,.000,,0,0,zelleco01
605,605,Ivica Zubac,C,24,LAC,76,1852,.626,3.4,,1.000,.580,.382,.032,.006,.000,,.626,.714,.508,.500,.333,,,.719,,,.248,110,,,,,0,0,zubaciv01

In [151]:
df2 = pd.read_csv('datasets/shootings_splits/SP_2021_2022.csv', keep_default_na=False, index_col=None)
df2.columns = df2.iloc[0]
df2 = df2.drop(df2.index[0])
df2.replace('', np.nan, inplace=True)
df2.dropna(axis=1, how='all', inplace=True)
df2.drop(df2.iloc[:, :-1], axis=1)
df2

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,2P,0-3,3-10,10-16,16-3P,3P,2P,0-3,3-10,10-16,16-3P,3P,2P,3P,%FGA,#,%3PA,3P%,Att.,#,-9999
1,1,Precious Achiuwa,C,22,TOR,73,1725,.439,10.2,.741,.348,.274,.085,.035,.259,.468,.614,.345,.373,.190,.359,.598,.964,.143,67,.429,.313,0,0,achiupr01
2,2,Steven Adams,C,28,MEM,76,1999,.547,2.9,.997,.693,.260,.042,.003,.003,.548,.632,.350,.438,.000,.000,.490,NaN,.143,48,.000,NaN,1,0,adamsst01
3,3,Bam Adebayo,C,24,MIA,56,1825,.557,7.0,.992,.395,.309,.200,.088,.008,.562,.771,.467,.404,.313,.000,.608,NaN,.181,119,.000,NaN,2,0,adebaba01
4,4,Santi Aldama,PF,21,MEM,32,360,.402,12.0,.636,.333,.205,.091,.008,.364,.560,.682,.444,.417,.000,.125,.638,1.000,.076,10,.229,.364,0,0,aldamsa01
5,5,LaMarcus Aldridge,C,36,BRK,47,1050,.550,12.3,.900,.210,.170,.240,.279,.100,.578,.729,.513,.509,.563,.304,.748,1.000,.039,18,.283,.308,0,0,aldrila01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,601,Thaddeus Young,PF,33,TOT,52,845,.518,7.7,.824,.382,.393,.026,.022,.176,.554,.625,.523,.286,.167,.354,.524,1.000,.037,7,.604,.483,0,0,youngth01
602,602,Trae Young,PG,23,ATL,76,2652,.460,16.5,.605,.159,.204,.116,.126,.395,.512,.620,.451,.469,.513,.382,.142,.223,.000,0,.048,.552,1,0,youngtr01
603,603,Omer Yurtseven,C,23,MIA,56,706,.526,5.8,.955,.437,.385,.113,.020,.045,.547,.722,.432,.357,.000,.091,.783,1.000,.178,39,.182,.000,0,0,yurtsom01
604,604,Cody Zeller,C,29,POR,27,355,.567,3.7,.956,.644,.267,.033,.011,.044,.593,.621,.542,.333,1.000,.000,.725,NaN,.211,16,.250,.000,0,0,zelleco01
605,605,Ivica Zubac,C,24,LAC,76,1852,.626,3.4,1.000,.580,.382,.032,.006,.000,.626,.714,.508,.500,.333,NaN,.719,NaN,.248,110,NaN,NaN,0,0,zubaciv01

In [141]:
columns_to_keep = df2.columns
result_df = result_df[columns_to_keep]

KeyError: "['-9999'] not in index"